name = "polls-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "polls"
database_id = "ab09afe9-11d7-4b0d-a284-da895e8fbe51"

migrations_dir = "migrations"

[vars]
ALLOWED_ORIGINS = "https://polls.gogel.io"
